# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  name: 'default'

variables:
  - name: RgName
    value: 'eburaso'
  - name: RgNameKey
    value: 'KeyVaultResources'
  - name: StorageAccount
    value: 'storagebura'
  - name : FileURL
    value : ''

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
    overrideParameters: '-storageAccountName $(StorageAccount)'
    deploymentMode: 'Validation'


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/LBvm/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/LBvm/azuredeploy.parameters.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deployment Vm scale set
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/WindowsVM/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/WindowsVM/azuredeploy.parameters.json'
    overrideParameters: '-adminPassword $(AdminPass)'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Ajout Extension VM
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/ExtensionVM/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/ExtensionVM/azuredeploy.parameters.json'
    overrideParameters: '-fileUris $(FileName)'
    deploymentMode: 'Validation'


- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deployment key vault
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgNameKey)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/keyVault/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/keyVault/azuredeploy.parameters.json'
    overrideParameters: '-secretValue $(AdminPass)'
    deploymentMode: 'Validation'
