# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  name: 'default'

variables:
  - name: RgName
    value: 'eburaso'
  - name: StorageAccount
    value: 'storagebura'

steps:
- script: |
    echo "Listing files in $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Verify files in source directory'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parametres.json'
    overrideParameters: '-storageAccountName $(StorageAccount)'
    deploymentMode: 'Validation'
