# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'default'

variables:
  - name: RgName
    value : 'eburaso'
  - name: RgNameKey
    value: 'KeyVaultResources'
  - name: StorageAccount
    value : 'storagebura'
  - name : FileName
    value: 'CustomExtension.ps1'
  - name : FileURL
    value : ''

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deployment storage account
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
    overrideParameters: '-storageAccountName $(StorageAccount)'
    deploymentMode: 'Complete'
    deploymentOutputs: 'StorageAccountDeployment'



- task: PowerShell@2
  displayName: Pushing PowerShell File onto Storage Account
  inputs:
    targetType: 'inline'
    script: |
            Write-Host $(StorageAccountDeployment.storageKey.Value)

            $context = New-AzStorageContext -StorageAccountName $(StorageAccount) -StorageAccountKey $(StorageAccountDeployment.storageKey.Value)
            $setParams = @{
                Container =  'blob'
                File      = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine('$(Build.SourcesDirectory)', './StorageAccount/$(FileName)'))
                Context   = $context
            }
            Write-Host $setParams.File

            $blob = Set-AzStorageBlobContent @setParams -Force
            $url = $blob.ICloudBlob.Uri.AbsoluteUri

            Write-Host $url

            Write-Host "##vso[task.setvariable variable=FileURL]$url"

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deployment LBvm
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/LBvm/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/LBvm/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deployment Vm scale set
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/WindowsVM/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/WindowsVM/azuredeploy.parameters.json'
    overrideParameters: '-adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: ajout Extension VM
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgName)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/ExtensionVM/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/ExtensionVM/azuredeploy.parameters.json'
    overrideParameters: '-fileUris $(FileName)'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deployment key vault
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f224499d-9e08-44eb-80e4-92cba7013495)'
    subscriptionId: 'f224499d-9e08-44eb-80e4-92cba7013495'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(RgNameKey)'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/keyVault/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/keyVault/azuredeploy.parameters.json'
    overrideParameters: '-secretValue $(AdminPass)'
    deploymentMode: 'Incremental'
